name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on:  [self-hosted, macOS]

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: swift test 2>&1 | xcbeautify
